# generated by datamodel-codegen:
#   filename:  events.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, Field, RootModel, confloat


class Word(BaseModel):
    w: str = Field(
        ..., description='The word, punctuated/cased as the provider returns it'
    )
    start: float = Field(
        ...,
        description='Audio-time seconds from first audio sample of the session; monotonic across failover (adapters apply the session offset)',
    )
    end: float
    conf: confloat(ge=0.0, le=1.0) | None = None
    speaker: int | None = Field(
        None, description='Speaker index when diarization on; absent otherwise'
    )
    lang: str | None = Field(
        None, description='BCP-47, present only for multilingual models'
    )


class SessionOpen(BaseModel):
    """
    server->client, first message after WS accept
    """

    type: Literal['session.open']
    session_id: str
    model: str = Field(..., description='Resolved slug, e.g. deepgram/nova-3')
    encoding: str | None = None
    sample_rate: int | None = None


class Transcript(BaseModel):
    """
    server->client, the core event
    """

    type: Literal['transcript']
    is_final: bool
    text: str
    words: list[Word] | None = None
    start: float | None = None
    end: float | None = None
    lang: str | None = None
    provider_raw: dict[str, Any] | None = Field(
        None,
        description='Optional passthrough of provider payload, only when ?include_raw=true',
    )


class SpeechStarted(BaseModel):
    type: Literal['speech_started']
    at: float


class UtteranceEnd(BaseModel):
    """
    Endpointing signal — the voice-agent trigger to respond
    """

    type: Literal['utterance_end']
    at: float


class ProviderSwitched(BaseModel):
    """
    Mid-stream failover happened; transcripts continue in same schema. DEDUP GUARANTEE: the gateway suppresses final transcripts from the new provider covering audio time already delivered as final — clients never receive duplicate finals for the same audio range. Interim events may re-cover replayed audio; standard interim semantics apply (superseded by the next final).
    """

    type: Literal['provider_switched']
    from_: str = Field(..., alias='from')
    to: str
    resumed_at: float = Field(
        ..., description='Audio-time seconds replayed from ring buffer'
    )
    speaker_mapping_preserved: bool = Field(
        ...,
        description='false: speaker indices reset with the new provider (client must treat labels as a new epoch). true: gateway aligned old/new labels via ring-buffer overlap and indices remain comparable. v1 always emits false; true is a forward-compatible upgrade.',
    )


class TextDelta(BaseModel):
    """
    client->server on /v1/speak: a chunk of text to synthesize. Text stays JSON (small); synthesized audio returns as binary frames.
    """

    type: Literal['text.delta']
    text: str


class Clear(BaseModel):
    """
    client->server on /v1/speak: barge-in. Discard all queued/undelivered synthesis immediately; server responds with `cleared`. Essential for voice-agent interruption.
    """

    type: Literal['clear']


class Cleared(BaseModel):
    """
    server->client on /v1/speak: ack for `clear`. Chunks with seq <= last_seq are stale (client discards any it has buffered); chunks after belong to post-clear synthesis.
    """

    type: Literal['cleared']
    last_seq: int


class KeepAlive(BaseModel):
    """
    client->server on either socket: hold the session open during audio/text silence. Needed because browser WebSocket API cannot send protocol-level pings. Send every ~8s of inactivity; sessions idle beyond the server's limit close with error audio_timeout.
    """

    type: Literal['keepalive']


class AudioChunk(BaseModel):
    """
    TTS /v1/speak server->client; audio itself travels as binary WS frames, this JSON frame precedes each with timing metadata
    """

    type: Literal['audio.chunk']
    seq: int
    start: float | None = None
    word_timestamps: list[Word] | None = None


class Finalize(BaseModel):
    """
    client->server: flush and finish (STT) / end of text input (TTS)
    """

    type: Literal['finalize']


class Usage(BaseModel):
    audio_seconds: float | None = None
    characters: int | None = None
    model: str | None = None
    cost_usd: float | None = None


class Done(BaseModel):
    """
    server->client, last message before close
    """

    type: Literal['done']
    usage: Usage


class Code(Enum):
    """
    Closed, stable set. REST endpoints wrap the same codes in an OpenAI-compatible {error:{code,message,type}} envelope.
    """

    auth_failed = 'auth_failed'
    key_revoked = 'key_revoked'
    insufficient_credits = 'insufficient_credits'
    rate_limited = 'rate_limited'
    concurrency_exceeded = 'concurrency_exceeded'
    invalid_request = 'invalid_request'
    model_not_found = 'model_not_found'
    unsupported_capability = 'unsupported_capability'
    unsupported_encoding = 'unsupported_encoding'
    payload_too_large = 'payload_too_large'
    provider_error = 'provider_error'
    provider_timeout = 'provider_timeout'
    all_providers_failed = 'all_providers_failed'
    audio_timeout = 'audio_timeout'
    session_expired = 'session_expired'
    internal_error = 'internal_error'


class Error(BaseModel):
    type: Literal['error']
    code: Code = Field(
        ...,
        description='Closed, stable set. REST endpoints wrap the same codes in an OpenAI-compatible {error:{code,message,type}} envelope.',
    )
    message: str
    provider: str | None = None
    recoverable: bool | None = Field(
        None, description='true = stream continues (e.g. failover in progress)'
    )


class SpeechrouterWebsocketProtocolV0(
    RootModel[
        SessionOpen
        | Transcript
        | SpeechStarted
        | UtteranceEnd
        | ProviderSwitched
        | AudioChunk
        | TextDelta
        | Clear
        | Cleared
        | KeepAlive
        | Finalize
        | Done
        | Error
    ]
):
    root: (
        SessionOpen
        | Transcript
        | SpeechStarted
        | UtteranceEnd
        | ProviderSwitched
        | AudioChunk
        | TextDelta
        | Clear
        | Cleared
        | KeepAlive
        | Finalize
        | Done
        | Error
    ) = Field(
        ...,
        description='Every JSON message on WSS /v1/listen and /v1/speak, discriminated by `type`. FRAMING: audio always travels as raw binary WS frames (client->server on /v1/listen, server->client on /v1/speak); ALL JSON events travel as text frames — a text frame is always an event in this schema, a binary frame is always audio. TIME BASE: every timestamp is audio-time seconds from the first audio sample of the session (not wall clock, not provider-native), monotonic across provider failover.',
        title='SpeechRouter WebSocket Protocol v0',
    )
